In [2]:
import numpy as np

In [3]:
what_type = np.array([[6, 15.7], [True, False]])

In [4]:
what_type.dtype

dtype('float64')

In [12]:
monthly_sales = np.array([[ 4134, 23925,  8657],
                        [ 4116, 23875,  9142],
                        [ 4673, 27197, 10645],
                        [ 4580, 25637, 10456],
                        [ 5109, 27995, 11299],
                        [ 5011, 27419, 10625],
                        [ 5245, 27305, 10630],
                        [ 5270, 27760, 11550],
                        [ 4680, 24988,  9762],
                        [ 4913, 25802, 10456],
                        [ 5312, 25405, 13401],
                        [ 6630, 27797, 18403]])

### This is key: axis=0 USUALLY refers to rows, and axis=1 USUALLY refers to columns. However, with aggregating functions, think of what shape the END result will be. 
- If you are summing rows, for example, the end result will be another COLUMN of values
    - Paradoxically, this will make it **"axis=1"** 

Check it out:

In [6]:
monthly_sales.sum(axis=1)

array([36716, 37133, 42515, 40673, 44403, 43055, 43180, 44580, 39430,
       41171, 44118, 52830])

In [10]:
# but let's keep the original dimensions
sales_totals = monthly_sales.sum(axis=1, keepdims=True)
print(sales_totals)

[[36716]
 [37133]
 [42515]
 [40673]
 [44403]
 [43055]
 [43180]
 [44580]
 [39430]
 [41171]
 [44118]
 [52830]]


In [14]:
# Now let's append sales_totals to monthly_sales
monthly_sales_plus_totals = np.append(monthly_sales, sales_totals, axis=1)

#...and as you can see, axis=1 means we're appending to the columns
print(monthly_sales_plus_totals)

[[ 4134 23925  8657 36716]
 [ 4116 23875  9142 37133]
 [ 4673 27197 10645 42515]
 [ 4580 25637 10456 40673]
 [ 5109 27995 11299 44403]
 [ 5011 27419 10625 43055]
 [ 5245 27305 10630 43180]
 [ 5270 27760 11550 44580]
 [ 4680 24988  9762 39430]
 [ 4913 25802 10456 41171]
 [ 5312 25405 13401 44118]
 [ 6630 27797 18403 52830]]


 And here, we're going to do the same thing, but take the mean of the columns.
 - This results in a 1D array. Because the mean of the columns is an action upon the rows, we'll use **_axis=0_**

In [20]:
# Note: We need keepdims=True to keep the dimensions because even though it looks like a 1D array will work to append,
# it really will not.
avg_monthly_sales = monthly_sales.mean(axis=0, keepdims=True) 
print(avg_monthly_sales)

[[ 4972.75       26258.75       11252.16666667]]


In [21]:
# Now let's append avg_monthly_sales to monthly_sales
# Note: this is only possible because we have maintained the 2D shape above.

monthly_sales_plus_avg = np.concatenate([monthly_sales, avg_monthly_sales], axis=0)
print(monthly_sales_plus_avg)

[[ 4134.         23925.          8657.        ]
 [ 4116.         23875.          9142.        ]
 [ 4673.         27197.         10645.        ]
 [ 4580.         25637.         10456.        ]
 [ 5109.         27995.         11299.        ]
 [ 5011.         27419.         10625.        ]
 [ 5245.         27305.         10630.        ]
 [ 5270.         27760.         11550.        ]
 [ 4680.         24988.          9762.        ]
 [ 4913.         25802.         10456.        ]
 [ 5312.         25405.         13401.        ]
 [ 6630.         27797.         18403.        ]
 [ 4972.75       26258.75       11252.16666667]]


## This is super-useful -- vectorizing functions

In [23]:
names = np.array([["Izzy", "Monica", "Marvin"],
                  ["Weber", "Patel", "Hernandez"]])

# Vectorize the .upper() string method
vectorized_upper = np.vectorize(str.upper) # make sure to use str.upper, not .upper

# Apply vectorized_upper to the names array
uppercase_names = vectorized_upper(names)
print(uppercase_names)

[['IZZY' 'MONICA' 'MARVIN']
 ['WEBER' 'PATEL' 'HERNANDEZ']]
